# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTasarim' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSTasarim
  pod 'STTabbar'
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'

  target 'iOSTasarimTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSTasarimUITests' do
    # Pods for testing
  end

end
